export const theme = {
    colors: {
      primary: '#3498db',
      primaryLight: '#5dade2',
      primaryDark: '#2874a6',
      secondary: '#2c3e50',
      secondaryLight: '#34495e',
      secondaryDark: '#1a252f',
      accent: '#e74c3c',
      accentLight: '#ec7063',
      accentDark: '#c0392b',
      light: '#ecf0f1',
      dark: '#2c3e50',
      white: '#ffffff',
      black: '#000000',
      gray: '#95a5a6',
      success: '#2ecc71',
      warning: '#f39c12',
      danger: '#e74c3c',
    },
    fonts: {
      primary: "'Poppins', sans-serif",
      secondary: "'Open Sans', sans-serif",
    },
    fontSizes: {
      small: '0.8rem',
      medium: '1rem',
      large: '1.2rem',
      xlarge: '1.5rem',
      xxlarge: '2rem',
      xxxlarge: '3rem',
    },
    spacing: {
      small: '0.5rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '3rem',
    },
    breakpoints: {
      mobile: '576px',
      tablet: '768px',
      desktop: '992px',
      largeDesktop: '1200px',
    },
    shadows: {
      small: '0 2px 4px rgba(0,0,0,0.1)',
      medium: '0 4px 8px rgba(0,0,0,0.1)',
      large: '0 8px 16px rgba(0,0,0,0.1)',
    },
    transitions: {
      fast: '0.2s ease',
      medium: '0.4s ease',
      slow: '0.6s ease',
    },
  };